# Generated by Django 4.2.16 on 2024-10-02 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_rename_cursereview_coursereview"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursereview",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="course.course",
            ),
            preserve_default=False,
        ),
    ]
