# Generated by Django 4.2.16 on 2024-09-29 15:01

import app.users.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", app.users.managers.CustomUserManager()),
            ],
        ),
    ]
